using Match3.Core;
using Match3.Game;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Match3.UI
{
    /// <summary>
    /// The "Candy Town" decor meta (menu only), Royal-Match-lite: the current
    /// chapter's scene rebuilds itself automatically as that chapter's stars come in
    /// — five cumulative stages, no choices, purely cosmetic. Scene sprites are
    /// generated by the sprite menu (Resources/UI/Town); until they exist the panel
    /// shows a friendly placeholder.
    /// </summary>
    public sealed class TownPanel : MonoBehaviour
    {
        private static readonly Color OverlayColor = new Color(0f, 0f, 0f, 0.78f);

        private static readonly string[] ChapterNames =
        {
            "CHAPTER 1 — PURPLE NIGHT",
            "CHAPTER 2 — OCEAN TEAL",
            "CHAPTER 3 — DUSK PLUM",
            "CHAPTER 4 — EMBER DAWN",
            "CHAPTER 5 — CANDY GARDEN",
        };

        private GameObject _root;
        private Image _card;
        private TMP_Text _chapterLine;
        private Image _scene;
        private TMP_Text _placeholder;
        private TMP_Text _starsLine;
        private TMP_Text _nextLine;
        private TMP_Text _celebration;
        private RectTransform _barFill;

        public static TownPanel Attach(Canvas canvas, Transform buttonHost)
        {
            var host = new GameObject(nameof(TownPanel), typeof(RectTransform));
            host.transform.SetParent(canvas.transform, false);
            var hostRect = (RectTransform)host.transform;
            hostRect.anchorMin = Vector2.zero;
            hostRect.anchorMax = Vector2.one;
            hostRect.sizeDelta = Vector2.zero;

            host.SetActive(false);
            var panel = host.AddComponent<TownPanel>();
            panel.Build();
            panel.BuildOpener(buttonHost);
            panel.Hide();
            host.SetActive(true);
            return panel;
        }

        private void Refresh()
        {
            var catalog = Resources.Load<LevelCatalog>("LevelCatalog");
            int levelCount = catalog != null ? catalog.Count : 20;
            int chapterCount = Mathf.Max(1, levelCount / ThemeCurve.ChapterLength);
            int chapter = Mathf.Clamp((ProgressService.Current.HighestUnlocked - 1) / ThemeCurve.ChapterLength,
                                      0, chapterCount - 1);

            int chapterStars = 0;
            int firstLevel = chapter * ThemeCurve.ChapterLength + 1;
            for (int level = firstLevel; level < firstLevel + ThemeCurve.ChapterLength; level++)
                chapterStars += ProgressService.Current.StarsFor(level);

            int stage = TownRules.StageFor(chapterStars);
            _chapterLine.text = ChapterNames[Mathf.Clamp(chapter, 0, ChapterNames.Length - 1)];
            _starsLine.text = $"Chapter stars: {chapterStars}/{ThemeCurve.ChapterLength * 3}";
            _barFill.anchorMax = new Vector2(Mathf.Clamp01(chapterStars / (float)(TownRules.StageCount * TownRules.StarsPerStage)), 1f);
            _nextLine.text = stage >= TownRules.StageCount
                ? "The town is complete!"
                : $"Next stage: {TownRules.StarsToNextStage(chapterStars)} stars away"; // no '★' glyph in the fonts

            Sprite sceneSprite = stage > 0 ? Resources.Load<Sprite>($"UI/Town/town_stage{stage}") : null;
            _scene.enabled = sceneSprite != null;
            _scene.sprite = sceneSprite;
            _placeholder.text = stage == 0
                ? "Win stars in this chapter to build the town!"
                : (sceneSprite == null ? "Scene art pending:\nMatch3 > Generate > Candy Sprites" : string.Empty);

            // One-shot celebration when a stage newly unlocked since the last look.
            int globalStage = TownRules.GlobalStage(chapter, chapterStars);
            bool isNew = globalStage > MetaService.Current.LastSeenTownStage;
            _celebration.text = isNew ? "NEW STAGE UNLOCKED!" : string.Empty;
            if (isNew)
            {
                MetaService.Current.LastSeenTownStage = globalStage;
                MetaService.Save();
                AudioManager.Play(Sfx.Win);
            }
        }

        private void Show()
        {
            _card.color = UiTheme.ThemeCard;
            Refresh();
            UiTween.OpenPanel(this, _root, _card.transform);
        }

        private void Hide() => UiTween.ClosePanel(this, _root);

        private void OnOpenerClicked()
        {
            AudioManager.Play(Sfx.Button);
            if (_root.activeSelf) Hide();
            else Show();
        }

        // ---- Construction ---------------------------------------------------------------

        private void Build()
        {
            _root = CreateRect("Overlay", transform, Vector2.zero, Vector2.one, Vector2.zero);
            _root.AddComponent<Image>().color = OverlayColor;

            GameObject cardGo = CreateRect("Card", _root.transform, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f), new Vector2(880f, 1160f));
            _card = cardGo.AddComponent<Image>();
            UiTheme.ApplySprite(_card, UiTheme.Round, UiTheme.ThemeCard);
            Transform content = cardGo.transform;

            TMP_Text title = CreateText("Title", content, new Vector2(0f, 490f), 64f, FontStyles.Bold);
            UiTheme.ApplyFont(title, UiTheme.TitleFont);
            title.text = "CANDY TOWN";

            _chapterLine = CreateText("Chapter", content, new Vector2(0f, 410f), 30f, FontStyles.Bold);
            UiTheme.ApplyFont(_chapterLine, UiTheme.BodyFont);
            _chapterLine.color = UiTheme.Gold;
            _chapterLine.characterSpacing = 4f;

            // Scene box: dark frame + the (tinted-by-art) town sprite inside it.
            GameObject frameGo = CreateRect("SceneFrame", content, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f), new Vector2(760f, 470f));
            frameGo.GetComponent<RectTransform>().anchoredPosition = new Vector2(0f, 120f);
            var frame = frameGo.AddComponent<Image>();
            UiTheme.ApplySprite(frame, UiTheme.Round, UiTheme.Slot);
            frame.raycastTarget = false;

            var sceneGo = new GameObject("Scene", typeof(RectTransform), typeof(Image));
            sceneGo.transform.SetParent(frameGo.transform, false);
            var sceneRect = (RectTransform)sceneGo.transform;
            sceneRect.anchorMin = Vector2.zero;
            sceneRect.anchorMax = Vector2.one;
            sceneRect.offsetMin = new Vector2(14f, 14f);
            sceneRect.offsetMax = new Vector2(-14f, -14f);
            _scene = sceneGo.GetComponent<Image>();
            _scene.preserveAspect = false;
            _scene.raycastTarget = false;

            _placeholder = CreateText("Placeholder", frameGo.transform, Vector2.zero, 34f, FontStyles.Normal);
            _placeholder.color = UiTheme.TextDim;
            _placeholder.rectTransform.sizeDelta = new Vector2(640f, 200f);

            _celebration = CreateText("Celebration", content, new Vector2(0f, -160f), 40f, FontStyles.Bold);
            UiTheme.ApplyFont(_celebration, UiTheme.TitleFont);
            _celebration.color = UiTheme.Gold;

            _starsLine = CreateText("Stars", content, new Vector2(0f, -240f), 36f, FontStyles.Bold);
            UiTheme.ApplyFont(_starsLine, UiTheme.BodyFont);

            GameObject trackGo = CreateRect("Track", content, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f), new Vector2(620f, 30f));
            trackGo.GetComponent<RectTransform>().anchoredPosition = new Vector2(0f, -305f);
            var track = trackGo.AddComponent<Image>();
            UiTheme.ApplySprite(track, UiTheme.Pill, UiTheme.Slot);
            var fillGo = new GameObject("Fill", typeof(RectTransform), typeof(Image));
            fillGo.transform.SetParent(trackGo.transform, false);
            _barFill = (RectTransform)fillGo.transform;
            _barFill.anchorMin = Vector2.zero;
            _barFill.anchorMax = new Vector2(0f, 1f);
            _barFill.offsetMin = Vector2.zero;
            _barFill.offsetMax = Vector2.zero;
            var fill = fillGo.GetComponent<Image>();
            UiTheme.ApplySprite(fill, UiTheme.Pill, UiTheme.Gold);
            fill.raycastTarget = false;

            _nextLine = CreateText("Next", content, new Vector2(0f, -365f), 30f, FontStyles.Normal);
            UiTheme.ApplyFont(_nextLine, UiTheme.BodyFont);
            _nextLine.color = UiTheme.TextDim;

            GameObject closeGo = CreateRect("CloseButton", content, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f), new Vector2(600f, 110f));
            closeGo.GetComponent<RectTransform>().anchoredPosition = new Vector2(0f, -480f);
            var closeImage = closeGo.AddComponent<Image>();
            UiTheme.ApplySprite(closeImage, UiTheme.Pill, UiTheme.Slot);
            var closeButton = closeGo.AddComponent<Button>();
            closeGo.AddComponent<PressableButton>();
            closeButton.targetGraphic = closeImage;
            closeButton.onClick.AddListener(OnOpenerClicked);
            TMP_Text closeLabel = CreateText("Label", closeGo.transform, Vector2.zero, 42f, FontStyles.Normal);
            UiTheme.ApplyFont(closeLabel, UiTheme.ButtonFont);
            closeLabel.color = UiTheme.TextDim;
            closeLabel.text = "Close";
            Stretch(closeLabel.rectTransform);
        }

        private void BuildOpener(Transform buttonHost)
        {
            var go = new GameObject("TownButton", typeof(RectTransform), typeof(Image), typeof(Button));
            go.transform.SetParent(buttonHost, false);
            var rect = (RectTransform)go.transform;
            rect.anchorMin = rect.anchorMax = new Vector2(0f, 1f);
            rect.pivot = new Vector2(0f, 1f);
            rect.sizeDelta = new Vector2(200f, 76f);
            rect.anchoredPosition = new Vector2(24f, -200f); // under DAILY and TASKS

            var image = go.GetComponent<Image>();
            UiTheme.ApplySprite(image, UiTheme.Pill, UiTheme.Slot);
            var button = go.GetComponent<Button>();
            go.AddComponent<PressableButton>();
            button.targetGraphic = image;
            button.onClick.AddListener(OnOpenerClicked);

            TMP_Text label = CreateText("Label", go.transform, Vector2.zero, 34f, FontStyles.Bold);
            UiTheme.ApplyFont(label, UiTheme.ButtonFont);
            label.text = "TOWN";
            Stretch(label.rectTransform);
        }

        private static void Stretch(RectTransform rect)
        {
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = Vector2.zero;
            rect.offsetMax = Vector2.zero;
        }

        private static GameObject CreateRect(string name, Transform parent, Vector2 anchorMin, Vector2 anchorMax, Vector2 size)
        {
            var go = new GameObject(name, typeof(RectTransform));
            go.transform.SetParent(parent, false);
            var rect = go.GetComponent<RectTransform>();
            rect.anchorMin = anchorMin;
            rect.anchorMax = anchorMax;
            rect.sizeDelta = anchorMin == anchorMax ? size : Vector2.zero;
            return go;
        }

        private static TMP_Text CreateText(string name, Transform parent, Vector2 position, float fontSize, FontStyles style)
        {
            GameObject go = CreateRect(name, parent, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f), new Vector2(780f, 100f));
            go.GetComponent<RectTransform>().anchoredPosition = position;
            var text = go.AddComponent<TextMeshProUGUI>();
            text.fontSize = fontSize;
            text.fontStyle = style;
            text.alignment = TextAlignmentOptions.Center;
            text.color = Color.white;
            text.raycastTarget = false;
            return text;
        }
    }
}
